openapi: 3.0.3
info:
  title: Cadastro de Profissionais API
  description: Documentação da API de cadastro de profissionais CREA/PI
  version: 1.0.0
servers:
  - url: /api/cadastro
    description: Development server
paths:
  /:
    get:
      summary: Buscar todos os Profissionais Cadastrados
      description: Retorna uma lista de todos os profissionais cadastrados no sistema.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CadastroProfissionais'
    post:
      summary: Cadastrar Novo Profissional
      description: Cadastra um novo profissional no sistema.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroProfissionais'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CadastroProfissionais'
  /{id}:
    get:
      summary: Buscar um Profissional Cadastrado
      description: Retorna um profissional com base no ID fornecido.
      parameters:
        - in: path
          name: id
          description: ID do Profissional
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CadastroProfissionais'
    put:
      summary: Atualizar um Profissional Cadastrado
      description: Atualiza as informações de um profissional existente.
      parameters:
        - in: path
          name: id
          description: ID do Profissional
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CadastroProfissionais'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CadastroProfissionais'
    delete:
      summary: Deletar um Profissional Cadastrado
      description: Exclui um profissional do sistema com base no ID fornecido.
      parameters:
        - in: path
          name: id
          description: ID do Profissional
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
components:
  schemas:
    CadastroProfissionais:
      type: object
      properties:
        id:
          type: integer
        tipoCadastro:
          type: string
        nome:
          type: string
        cpf:
          type: string
        email:
          type: string
        password:
          type: string
        dataNascimento:
          type: string
          format: date
        telefone:
          type: string
        titulos:
          type: string
